version: 2.1

jobs:
  postman-test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout

      - run:
          name: Install Newman + htmlextra locally
          command: |
            npm init -y
            npm install newman newman-reporter-htmlextra

      - run:
          name: Create report folder
          command: mkdir -p report

      - run:
          name: Run Postman tests with HTML report
          command: |
            npx newman run tests/Lesson_5.postman_collection.json \
              -e tests/clickup.postman_environment.json \
              -r htmlextra \
              --reporter-htmlextra-export ./report/report.html

      - store_artifacts:
          path: report
          destination: postman-report

workflows:
  version: 2
  run-postman-tests:
    jobs:
      - postman-test